# -*- coding: utf-8 -*-
"""bruteforce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5BRx_EhSiVy199qWttwQwjUpgmmN7wQ
"""

import time
contraseña = "AVB"
minusculas = "abcdefghijklmnopqrstuvwxyz"
mayusculas = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
numeros    = "0123456789"
signos     = "!@#$%^&*()_+-=[]{}|;':\",./<>?`~ "
alfabeto = minusculas + mayusculas + numeros + signos
tiempo_inicio = time.time()
intentos = 0
encontrada = False
for longitud in range(1, len(contraseña) + 1):
    if encontrada:
        break
    indices = [0] * longitud
    total = len(alfabeto) ** longitud

    for num in range(total):
        intento = ""
        temp = num
        for i in range(longitud - 1, -1, -1):
            indices[i] = temp % len(alfabeto)
            temp //= len(alfabeto)
            intento += alfabeto[indices[i]]
        intentos += 1
        if intento == contraseña:
            encontrada = True
            tiempo_final = time.time()
            tiempo_transcurrido = tiempo_final - tiempo_inicio
            print(f" Contraseña acertada: {intento}")
            print(f" Intentos: {intentos}")
            print(f"Tiempo transcurrido: {tiempo_transcurrido: } segundos")
            break